export class BaremosGuardiaItem {
    guardias: String;
    nDias: String;
    baremo: String;
    dias: String;
    disponibilidad;
    numMinimoSimple;
    simpleOImporteIndividual;
    numDoblar;
    maximo;
    porDia: String;
    idFacturaciones: String[];
    idTurnos: String[];
    idGuardias: String[];
    fechabaja: Date;
    historico;
    precioHito;
    idInstitucion;
    idHito;
    nomturno:any;
    nomguardia:any;
    idTurno;
    idGuardia;
    idhitoconfiguracion;
    importeDis;
    dispAsuntosDis;
    aPartirDis;
    importeMaxDis;
    importeMinDis;
    aPartirMax;
    asiac;
    agruparAsAc;
    contAsiAsAc;
    contAcAsAc;
    importeAsAc;
    importeMinAsAc;
    importeMaxAsAc;
    importe;
    importeMax;
    agrupar;
    dispAsuntosAsAc;
}