export class BusquedaSancionesItem {
  nif: String;
  nombre: String;
  letrado: String;
  apellidos: String;
  primerApellido: String;
  segundoApellido: String;
  colegioSancionador: String;
  tipoSancion: String;
  refColegio: String;
  refConsejo: String;
  chkRehabilitado: boolean;
  fechaRehabilitado: Date;
  fecha: Date;
  fechaDesde: Date;
  fechaHasta: Date;
  chkArchivada: boolean;
  fechaArchivada: Date;
  fechaArchivadaDesde: Date;
  fechaArchivadaHasta: Date;
  tipo: String;
  origen: String;
  estado: String;
  chkFirmeza: boolean;
  fechaFirmeza: Date;
  fechaAcuerdo: Date;
  multa: String;
  texto: String;
  observaciones: String;
  constructor() {}
}
