export class DatosPlanUniversalItem {
	idInstitucion: String;
	idPersona: String;
	idLenguaje: String;
	NIF: String;
	denominacion: String;
	abreviatura: String;
	capitalObjetivo: String;
	fechaConstitucion: Date;
	titular: String;
	fechaAlta: Date;
	tipo: String;
	numeroIntegrantes: String;
	nombresIntegrantes: String;
	fechaBaja: Date;
	fechaInicio: Date;
	anotaciones: String;
	IDGrupos: String;
	sociedadProfesional: String;
	idioma: String;
	cuentaContable: String;
	grupos: String[];
	idLenguajeSociedad: String;
	motivo: String;
	error: Error;
	// Nuevos
	idEstadoSolicitud: String;
	idEstadoMutualista: String;
	nombre: String;
	sexo: String;
	idTratamiento: String;
	primerApellido: String;
	segundoApellido: String;
	fechaNacimiento: String;
	fechaNacConyuge: String;
	naturalDe: String;
	estadoCivil: String;
	numHijos: number;
	idPais: String;
	idpais: String;
	idProvincia: String;
	idPoblacion: String;
	domicilio: String;
	codigoPostal: String;
	telefono: String;
	movil: String;
	correoElectronico: String;
	cuentaBancaria: String;
	iban: String;
	hijos: String[];
	swift: String;
	periodicidadPago: String;
	idCobertura: String;
	cuotaMensual: String;
	idBeneficiario: number;
	idAsistenciaSanitaria: String;
	idEstadoCivil: String;
	pais: String;
	nombrePoblacion: String;
	bic: String;
	idBeneficiarios: String;
	dc: String;


	capitalcobertura: string;
	codigopostal: string;
	correoelectronico: string;
	cuotacobertura: string;
	telefono1: string;
	poblacion: string;
	cobertura: string;
	opcionCobertura: string;

	numerohijos: string;
	edadhijo1: string;
	edadhijo2: string;
	edadhijo3: string;
	edadhijo4: string;
	edadhijo5: string;
	edadhijo6: string;
	edadhijo7: string;
	edadhijo8: string;
	fechanacimientoconyuge: string;

	constructor() { }
}
