export class FichaColegialGeneralesItem {
  idPersona: String;
  nif: String;
  soloNombre: String;
  colegiado: Boolean;
  idTipoIdentificacion: String;
  nombre: String;
  apellidos1: String;
  apellidos2: String;
  sexo: String;
  idTratamiento: String;
  tratamiento: String;
  naturalDe: String;
  idEstadoCivil: String;
  estadoColegial: String;
  idLenguaje: String;
  situacion: String;
  fechaIncorporacionDate: Date;
  incorporacionDate: Date;
  fechaNacimientoDate: Date;
  fechaIncorporacion: Date;
  incorporacion: Date;
  fechaNacimiento: Date;
  idioma: String;
  motivo: String;
  asientoContable: String;
  partidoJudicial: any;
  publicarDatosContacto: boolean;
  comisiones: String;
  grupos: any[];
  etiquetas: any[];
  fechaBajaEtiq: Date;
  fechaInicioEtiq: Date;
  constructor() {}
}
