export const procesos_maestros: any = {
    zonasYSubzonas: '911',
    areasMaterias: '912',
    costesFijos: '915',
    juzgados: '91I',
    partidaPresupuesto: '113',
    fundamentoResolucion: '917',
    modulo: '91D',
    prisiones: '91G',
    comisarias: '91H',
    fundamentoCalificacion: '921',
    procuradores: '91F',
    partidaJudicial: '91C',
    documentacionEjg: '91J',
    calendarioLaboralAgenda: '939',
    procedimientos: '91P',
    tiposAsistencias: '99J',
    retenciones: '92S',
    tiposActuaciones: '99F',
    destinatariosRetenciones: '996'
};
