export const procesos_maestros: any = {
    zonasYSubzonas: 'MJGZO',
    areasMaterias: 'MJGAM',
    costesFijos: 'MJGCF',
    juzgados: 'MJGJU',
    partidaPresupuesto: 'MJGPP',
    fundamentoResolucion: 'MJGFR',
    modulo: 'MJGMO',
    prisiones: 'MJGPS',
    comisarias: 'MJGCO',
    fundamentoCalificacion: 'MJGFC',
    procuradores: 'MJGPR',
    partidaJudicial: 'MJGPJ',
    documentacionEjg: 'MJGDE',
    calendarioLaboralAgenda: 'MJGCL',
    procedimientos: 'MJGPD',
    tiposAsistencias: 'MJGTA',
    retenciones: 'MJGRE',
    tiposActuaciones: 'MJGTC',
    destinatariosRetenciones: 'MJGDR'
};
