export let endpoints_oficio: any = {
    fichaAreas_getJurisdicciones: "maestros/areasMaterias/jurisdicciones",
    combossjcs_comboAreas: "oficio/combossjcs/comboAreas",
    combossjcs_comboMaterias: "oficio/combossjcs/comboMaterias",
    combossjcs_comboTiposTurno: "oficio/combossjcs/comboTiposTurno",
    combossjcs_comboTiposGuardia: "oficio/combossjcs/comboTiposGuardia",
    combossjcs_comboZonas: "oficio/combossjcs/comboZonas",
    combossjcs_comboSubZonas: "oficio/combossjcs/comboSubZonas",
    combossjcs_comboPartidasPresupuestaria: "oficio/combossjcs/comboPartidasPresupuestaria",
    combossjcs_comboGruposFacturacion: "oficio/combossjcs/comboGruposFacturacion",
    turnos_busquedaTurnos: "oficio/turnos/busquedaTurnos",
    turnos_busquedaFichaTurnos: "oficio/turnos/busquedaFichaTurnos",
    turnos_eliminateTurnos: "oficio/turnos/eliminateTurnos",
    turnos_activarTurnos: "oficio/turnos/activarTurnos",
    turnos_updateDatosGenerales: "oficio/turnos/updateDatosGenerales",
    turnos_createnewTurno: "oficio/turnos/createnewTurno",
    fichaZonas_searchSubzones: "maestros/fichaZonas/searchSubzones",
    combossjcs_comboGuardias: "oficio/combossjcs/comboGuardias",
    combossjcs_ordenCola: "combo/ordenCola",
    combossjcs_comboRequisitosGuardias: "oficio/combossjcs/comboRequisitosGuardias",
    turnos_tarjetaGuardarPesos: "oficio/turnos/tarjetaGuardarPesos",
    turnos_tarjetaGuardarPesos2: "oficio/turnos/tarjetaGuardarPesos2",
    turnos_updateConfiguracion: "oficio/turnos/updateConfiguracion",
    turnos_busquedaColaOficio: "oficio/turnos/busquedaColaOficio",
    turnos_busquedaColaOficioPrimerLetrado: "oficio/turnos/busquedaColaOficioPrimerLetrado",
    turnos_eliminateColaOficio: "oficio/turnos/eliminateColaOficio",
    turnos_busquedaColaGuardia: "oficio/turnos/busquedaColaGuardia",
    combossjcs_comboidGuardias: "oficio/combossjcs/comboidGuardias",
    turnos_eliminateColaGuardia: "oficio/turnos/eliminateColaGuardia",
    turnos_busquedaGuardias: "oficio/turnos/busquedaGuardias",
    turnos_eliminateGuardia: "oficio/turnos/eliminateGuardia",
    turnos_updateUltimo: "oficio/turnos/updateUltimo",
    turnos_updateUltimoGuardias: "oficio/turnos/updateUltimoGuardias",
    turno_changeRequisitoGuardias: "oficio/turnos/changeRequisitoGuardias",
    //FIN DE TURNOS

    inscripciones_comboTurnos: "oficio/inscripciones/comboTurnos",
    inscripciones_busquedaInscripciones: "oficio/inscripciones/busquedaInscripciones",
    inscripciones_updateSolicitarBaja: "oficio/inscripciones/updateSolicitarBaja",
    inscripciones_busquedaTarjetaInscripciones: "oficio/inscripciones/busquedaTarjetaInscripciones",
    inscripciones_insertSolicitarAlta: "oficio/inscripciones/insertSolicitarAlta",
    inscripciones_checkTrabajosSJCS: "oficio/inscripciones/checkTrabajosSJCS",
    inscripciones_checkSaltos: "oficio/inscripciones/checkSaltos",
    inscripciones_updateBorrarSaltos: "oficio/inscripciones/updateBorrarSaltos",
    inscripciones_updateValidar: "oficio/inscripciones/updateValidar",
    inscripciones_updateDenegar: "oficio/inscripciones/updateDenegar",
    inscripciones_updateCambiarFecha: "oficio/inscripciones/updateCambiarFecha",
    inscripciones_TarjetaColaOficio: "oficio/inscripciones/TarjetaColaOficio",
    inscripciones_busquedaTarjeta: "oficio/inscripciones/busquedaTarjeta",
    //FIN DE INSCRIPCIONES

    bajasTemporales_comboEstado: "oficio/bajasTemporales/comboEstado",
    bajasTemporales_busquedaBajasTemporales: "oficio/bajasTemporales/busquedaBajasTemporales",
    bajasTemporales_updateBajaTemporal: "oficio/bajasTemporales/updateBaja",
    bajasTemporales_saveBajaTemporal: "oficio/bajasTemporales/saveBajaTemporal",
    bajasTemporales_nuevaBajaTemporal: "oficio/bajasTemporales/nuevaBajaTemporal",
    bajasTemporales_deleteBajaTemporal: "oficio/bajasTemporales/deleteBajaTemporal",
    //FIN DE BAJAS TEMPORALES

    //justificacion express
    justificacionExpres_busqueda: "oficio/busquedaJustificacionExpres",
    justificacionExpres_actualizacion: "oficio/actualizaJustificacionExpres",
    justificacionExpres_eliminacion: "oficio/eliminaJustificacionExpres",
    justificacionExpres_insercion: "oficio/insertaJustificacionExpres",
    justificacionExpres_getEJG: "oficio/getEJG",


    //CARGAS MASIVAS OFICIO
    busquedaGuardia_guardia: "combo/guardias",
    cargasMasivasOficio_decargarModelo: "oficio/cargasMasivasOficio/descargarModelo",
    cargasMasivasOficio_uploadFileIT: "oficio/cargasMasivasOficio/uploadFileIT",
    cargasMasivasOficio_uploadFileBT: "oficio/cargasMasivasOficio/uploadFileBT",

    //DESIGNAS
    designas_tipoDesignas: "oficio/designas/comboTipoDesigna",
    combo_comboJuzgadoDesignaciones: "combo/comboJuzgadoDesignaciones",
    combo_comboJuzgadoPorInstitucion: "combo/comboJuzgadoPorInstitucion",
    combo_comboModulosDesignaciones: "oficio/comboModulo",
    combo_comboDelitos: "oficio/designas/comboDelitos",
    combo_delitosDesigna: "oficio/designas/getDelitos",
    combo_comboProcedimientosDesignaciones: "oficio/comboProcedimientos",
    combo_comboProcedimientosConJuzgado: "oficio/comboProcedimientosConJuzgado",
    combo_comboAcreditacionesPorModulo: "combo/comboAcreditacionesPorModulo",
    combo_comboProcedimientosConModulo: "oficio/comboProcedimientosConModulo",
    combo_comboModulosConJuzgado: "oficio/comboModulosConJuzgado",
    combo_comboModulos: "oficio/comboModulo",
    combo_comboModulosAll: "oficio/comboAllModulos",
    combo_comboModulosConProcedimientos: "oficio/comboModulosConProcedimientos",
    designaciones_busqueda: "oficio/busquedaDesignaciones",
    designaciones_busquedaTotalRegistros: "oficio/busquedaTotalRegistrosDesignaciones",
    parametros_search: "parametros/search",
    designaciones_listaContrarios: "oficio/designas/busquedaListaContrarios",
    designaciones_listaInteresados: "oficio/designas/busquedaListaInteresados",
    designaciones_getDatosAdicionales: "oficio/designas/getDatosAdicionales",
    designaciones_comboPartidaPresupuestaria: "oficio/designas/comboPartidaPresupuestaria",
    designaciones_getDatosFacturacion: "oficio/designas/getPartidaPresupuestariaDesigna",
    designaciones_updateDatosAdicionales: "oficio/designas/updateDatosAdicionales",
    designaciones_busquedaProcedimiento: "oficio/busquedaProcedimientoDesignas",
    designaciones_busquedaModulo: "oficio/busquedaModuloDesignas",
    designaciones_busquedaJuzgado: "oficio/busquedaJuzgadoDesignas",
    designaciones_deleteContrario: "oficio/designas/deleteContrario",
    designaciones_deleteInteresado: "oficio/designas/deleteInteresado",
    designaciones_insertInteresado: "oficio/designas/insertInteresado",
    designaciones_insertContrario: "oficio/designas/insertContrario",
    create_NewDesigna: "oficio/designas/createnewDesigna",
    actuaciones_designacion: "oficio/designas/busquedaActDesigna",
    designaciones_busquedaProcurador: "oficio/designas/busquedaProcurador",
    designaciones_guardarProcurador: "oficio/designas/guardarProcurador",
    designaciones_comprobarProcurador: "oficio/designas/compruebaProcurador",
    designaciones_comprobarFechaProcurador: "oficio/designas/compruebaFechaProcurador",
    designaciones_guardarProcuradorEJG: "oficio/designas/guardarProcuradorEJG",
    designaciones_getEjgDesigna: "oficio/designas/getEjgDesigna",
    designaciones_motivosRenuncia: "oficio/designas/comboTipoMotivo",
    actuaciones_designacion_anular: "oficio/designas/anularActDesigna",
    actuaciones_designacion_reactivar: "oficio/designas/reactivarActDesigna",
    actuaciones_designacion_eliminar: "oficio/designas/eliminarActDesigna",
    actuaciones_designacion_guardar: "oficio/designas/guardarNewActDesigna",
    actuaciones_designacion_editar: "oficio/designas/actualizarActDesigna",
    actuaciones_designacion_numProcedimiento : "oficio/desgignas/formatoProcedimiento",
    actuaciones_designacion_validar: "oficio/designas/validarActDesigna",
    actuaciones_designacion_desvalidar: "oficio/designas/desvalidarActDesigna",
    actuaciones_designacion_updateJustiActDesigna: "oficio/designas/updateJustiActDesigna",
    actuaciones_designacion_getHistorioAccionesActDesigna: "oficio/designas/getHistorioAccionesActDesigna",
    actuaciones_designacion_getDocumentosPorActDesigna: "oficio/designas/getDocumentosPorActDesigna",
    actuaciones_designacion_descargarDocumentosActDesigna: "oficio/designas/descargarDocumentosActDesigna",
    actuaciones_designacion_descargarDocumentosActDesignaJustificacionExpres: "oficio/designas/descargarDocumentosActDesignaJustificacionExpres",
    actuaciones_designacion_eliminarDocumentosActDesigna: "oficio/designas/eliminarDocumentosActDesigna",
    actuaciones_designacion_getLetradoDesigna: "oficio/designas/getLetradoDesigna",
    actuaciones_designacion_subirDocumentoActDesigna: "oficio/designas/subirDocumentoActDesigna",
    actuaciones_designacion_actualizarPartidaPresupuestariaActDesigna: "oficio/designas/actualizarPartidaPresupuestariaActDesigna",
    combo_motivosCambio_actuDesigna: "oficio/comboMotivosCambioActDesigna",
    combo_prisiones: "oficio/comboPrisiones",
    combo_comboTipoDocDocumentacionDesigna: "combo/comboTipoDocumentacionDesigna",
    designaciones_updateRepresentanteInteresado:"oficio/designas/updateRepresentanteInteresado",
    designaciones_updateRepresentanteContrario:"oficio/designas/updateRepresentanteContrario",
    designaciones_updateAbogadoContrario:"oficio/designas/updateAbogadoContrario",
    designaciones_updateProcuradorContrario:"oficio/designas/updateProcuradorContrario",
    designaciones_updateDetalleDesignacion:"oficio/designas/updateDetalleDesignacion",
    designaciones_searchAbogadoByIdPersona:"oficio/designas/searchAbogadoByIdPersona",
    designacionesBusquedaRelaciones:"oficio/designas/busquedaRelaciones",
    designaciones_eliminarRelacion:"oficio/designas/eliminarRelacion",
    designaciones_eliminarRelacionAsistenciaDes:"oficio/designas/eliminarRelacionAsistenciaDesigna",
    designaciones_busquedaDesignacionActual:"oficio/designas/busquedaDesignacionActual",
    designaciones_busquedaLetradosDesignacion:"oficio/designas/busquedaLetradosDesignacion",
    designaciones_eliminarDesignaciones:"oficio/designas/deleteDesigna",
    designaciones_updateDesigna:"oficio/designas/updateDesigna",
    designaciones_busquedaNueva:"oficio/busquedaNuevaDesigna",
    designacionesBusquedaComunicaciones: "oficio/designas/busquedaComunicaciones",
    designaciones_updateLetradoDesignacion:"oficio/designas/updateLetradoDesigna",
    designaciones_compruebaLetradoInscritoEnTurno:"oficio/designas/compruebaLetradoInscritoEnTurno",
    designaciones_updateDatosFacturacion: "oficio/designas/updatePartidaPresupuestaria",
    designacion_getDocumentosPorDesigna: "oficio/designas/getDocumentosPorDesigna",
    designacion_subirDocumentoDesigna: "oficio/designas/subirDocumentoDesigna",
    designacion_subirDocumentoDesignaJustificacionExpres: "oficio/designas/subirDocumentoDesignaJustificacionExpres",
    designacion_eliminarDocumentosDesigna: "oficio/designas/eliminarDocumentosDesigna",
    designacion_descargarDocumentosDesigna: "oficio/designas/descargarDocumentosDesigna",
    designacion_descargarDocumentosDesignaJustificacionExpres: "oficio/designas/descargarDocumentosDesignaJustificacionExpres",
    designacion_asociarEjgDesigna: "oficio/designas/asociarEjgDesigna",
    designacion_asociarAsistenciaDesigna: "oficio/designas/asociarAsistenciaDesigna",
    designacion_getPreDesignaEJG: "oficio/designas/getPreDesignaEJG",
  
    designacion_queryImprimirJustificacionExpres :"oficio/designas/queryImprimirJustificacionExpress",

    //SALTOS Y COMPENSACIONES
    saltosCompensacionesOficio_buscar: "oficio/saltosCompensaciones/buscarSaltosOCompensaciones",
    saltosCompensacionesOficio_guardar: "oficio/saltosCompensaciones/guardarSaltosCompensaciones",
    saltosCompensacionesOficio_anular: "oficio/saltosCompensaciones/anularSaltosCompensaciones",
    saltosCompensacionesOficio_borrar: "oficio/saltosCompensaciones/borrarSaltosCompensaciones",
    saltosCompensacionesOficio_comboColegiados: "oficio/saltosCompensaciones/searchLetradosTurno",



    designaciones_existeDesignaJuzgadoProcedimiento:"oficio/designas/existeDesginaJuzgadoProcedimiento",
    designaciones_recuperarParamentoGen:"oficio/designas/recuperarParamentoGen"
}