export let endpoints_EJG_Comision: any = {
    busquedaCol_colegioComision: "ejgComision/filtros-ejg/colegioComision",
    filtrosejg_comboTipoEJGColegioComision: "ejgComision/filtros-ejg/comboTipoEJGColegioComision",
    combo_guardiaPorTurnoComision: "ejgComision/filtros-ejg/guardias/",
    busquedaFundamentosCalificacion_comboDictamenComision: "ejgComision/filtros-ejg/comboDictamenComision",
    filtrosejgcomision_comboEJGColegioComision: "ejgComision/filtros-ejg/comboEJGColegioComision",
    filtrosejgcomision_comboEstadoEJGComision: "ejgComision/filtros-ejg/comboEstadoEJGComision",
    filtrosejgcomision_comboAnioActaComision: "ejgComision/filtros-ejg/comboAnioActaComision",
    filtrosejgcomision_comboResolucionComision: "ejgComision/filtros-ejg/comboResolucionComision",
    filtrosejgcomision_comboFundamentoJuridComision: "ejgComision/filtros-ejg/comboFundamentoJuridComision",
    filtrosejgcomision_busquedaEJGComision: "ejgComision/filtros-ejg/busquedaEJGComision",
    filtrosejgcomision_comboJuzgadosComision: "ejgComision/filtros-ejg/comboJuzgadosComision",
    filtrosejgcomision_comboPonenteComision: "ejgComision/filtros-ejg/comboPonenteComision",
    filtrosejgcomision_comboTurnoComision: "ejgComision/filtros-ejg/comboTurnosTipoComision",
    postDatosActualizarComision: "ejgComision/filtros-ejg/datosActualizar",
    obligatoriedadResolucion: "ejgComision/filtros-ejg/obligatoriedadResolucion",
    filtrosejgcomision_comboPresidente: "ejgComision/filtros-ejg/comboPresidente",
    filtrosejgcomision_comboSecretario: "ejgComision/filtros-ejg/comboSecretario",
    filtrosacta_busquedaActas: "acta/filtros-acta/busquedaActas",
    filtrosejgcomision_editarResolucionFundamento: "ejgComision/filtros-ejg/editarResolucionFundamento",
    filtrosejgcomision_borrarResolucionFundamento: "ejgComision/filtros-ejg/borrarResolucionFundamento",
    filtrosejgcomision_editarPonente: "ejgComision/filtros-ejg/editarPonente",
    filtrosejgcomision_borrarPonente: "ejgComision/filtros-ejg/borrarPonente",
    filtrosejgcomision_editarActaAnio: "ejgComision/filtros-ejg/editarActaAnio",
    filtrosejgcomision_borrarActaAnio: "ejgComision/filtros-ejg/borrarActaAnio",
    filtrosejgcomision_obligatorioFundamento: "ejgComision/filtros-ejg/obligatorioFundamento",
    filtrosacta_comboSufijo: "acta/filtros-acta/comboSufijoActa",
    filtrosacta_anadirEJGPendientesCAJG: "acta/filtros-acta/anadirEJGPendientesCAJG",
    filtrosacta_guardarActa: "acta/filtros-acta/guardarActa",
    filtrosacta_getActa: "acta/filtros-acta/getActa",
    filtrosacta_borrar: "acta/filtros-acta/borrarActas",
    filtrosacta_abrirActa: "acta/filtros-acta/abrirActa",
    filtrosacta_cerrarActa: "acta/filtros-acta/cerrarActa",
    filtrosacta_getNumAca: "acta/filtros-acta/getNumActa",
    filtrosacta_getAbreviatura: "acta/filtros-acta/getAbreviatura",
    filtrosejgcomision_busquedaEJGActaComision: "ejgComision/filtros-ejg/busquedaEJGActaComision",
    busquedaejgcomision_asociarEJGActa: "ejgComision/busqueda-ejg-comision/asociarEJGActa"



}
