export let endpoints_oficio: any = {
    fichaAreas_getJurisdicciones: "maestros/areasMaterias/jurisdicciones",
    combossjcs_comboAreas: "oficio/combossjcs/comboAreas",
    combossjcs_comboMaterias: "oficio/combossjcs/comboMaterias",
    combossjcs_comboTiposTurno: "oficio/combossjcs/comboTiposTurno",
    combossjcs_comboTiposGuardia: "oficio/combossjcs/comboTiposGuardia",
    combossjcs_comboZonas: "oficio/combossjcs/comboZonas",
    combossjcs_comboSubZonas: "oficio/combossjcs/comboSubZonas",
    combossjcs_comboPartidasPresupuestaria: "oficio/combossjcs/comboPartidasPresupuestaria",
    combossjcs_comboGruposFacturacion: "oficio/combossjcs/comboGruposFacturacion",
    turnos_busquedaTurnos: "oficio/turnos/busquedaTurnos",
    turnos_busquedaFichaTurnos: "oficio/turnos/busquedaFichaTurnos",
    turnos_eliminateTurnos: "oficio/turnos/eliminateTurnos",
    turnos_updateDatosGenerales: "oficio/turnos/updateDatosGenerales",
    turnos_createnewTurno: "oficio/turnos/createnewTurno",
    fichaZonas_searchSubzones: "maestros/fichaZonas/searchSubzones",
    combossjcs_comboGuardias: "oficio/combossjcs/comboGuardias",
    combossjcs_ordenCola: "combo/ordenCola",
    combossjcs_comboRequisitosGuardias: "oficio/combossjcs/comboRequisitosGuardias",
    turnos_tarjetaGuardarPesos: "oficio/turnos/tarjetaGuardarPesos"
}