export let endpoints_oficio: any = {
    fichaAreas_getJurisdicciones: "maestros/areasMaterias/jurisdicciones",
    combossjcs_comboAreas: "oficio/combossjcs/comboAreas",
    combossjcs_comboMaterias: "oficio/combossjcs/comboMaterias",
    combossjcs_comboTiposTurno: "oficio/combossjcs/comboTiposTurno",
    combossjcs_comboTiposGuardia: "oficio/combossjcs/comboTiposGuardia",
    combossjcs_comboZonas: "oficio/combossjcs/comboZonas",
    combossjcs_comboSubZonas: "oficio/combossjcs/comboSubZonas",
    combossjcs_comboPartidasPresupuestaria: "oficio/combossjcs/comboPartidasPresupuestaria",
    combossjcs_comboGruposFacturacion: "oficio/combossjcs/comboGruposFacturacion",
    turnos_busquedaTurnos: "oficio/turnos/busquedaTurnos",
    turnos_busquedaFichaTurnos: "oficio/turnos/busquedaFichaTurnos",
    turnos_eliminateTurnos: "oficio/turnos/eliminateTurnos",
    turnos_updateDatosGenerales: "oficio/turnos/updateDatosGenerales",
    turnos_createnewTurno: "oficio/turnos/createnewTurno",
    fichaZonas_searchSubzones: "maestros/fichaZonas/searchSubzones",
    combossjcs_comboGuardias: "oficio/combossjcs/comboGuardias",
    combossjcs_ordenCola: "combo/ordenCola",
    combossjcs_comboRequisitosGuardias: "oficio/combossjcs/comboRequisitosGuardias",
    turnos_tarjetaGuardarPesos: "oficio/turnos/tarjetaGuardarPesos",
    turnos_tarjetaGuardarPesos2: "oficio/turnos/tarjetaGuardarPesos2",
    turnos_updateConfiguracion: "oficio/turnos/updateConfiguracion",
    turnos_busquedaColaOficio: "oficio/turnos/busquedaColaOficio",
    turnos_eliminateColaOficio: "oficio/turnos/eliminateColaOficio",
    turnos_busquedaColaGuardia: "oficio/turnos/busquedaColaGuardia",
    combossjcs_comboidGuardias: "oficio/combossjcs/comboidGuardias",
    turnos_eliminateColaGuardia: "oficio/turnos/eliminateColaGuardia",
    turnos_busquedaGuardias: "oficio/turnos/busquedaGuardias",
    turnos_eliminateGuardia: "oficio/turnos/eliminateGuardia",
    turnos_updateUltimo: "oficio/turnos/updateUltimo",
    turno_changeRequisitoGuardias: "oficio/turnos/changeRequisitoGuardias",
    //FIN DE TURNOS

    inscripciones_comboTurnos: "oficio/inscripciones/comboTurnos",
    inscripciones_busquedaInscripciones:"oficio/inscripciones/busquedaInscripciones",
    inscripciones_updateSolicitarBaja:"oficio/inscripciones/updateSolicitarBaja",
    inscripciones_busquedaTarjetaInscripciones:"oficio/inscripciones/busquedaTarjetaInscripciones",
    inscripciones_insertSolicitarAlta:"oficio/inscripciones/insertSolicitarAlta",
    inscripciones_checkTrabajosSJCS:"oficio/inscripciones/checkTrabajosSJCS",
    inscripciones_checkSaltos:"oficio/inscripciones/checkSaltos",
    inscripciones_updateBorrarSaltos:"oficio/inscripciones/updateBorrarSaltos",
    inscripciones_updateValidar:"oficio/inscripciones/updateValidar",
    inscripciones_updateDenegar:"oficio/inscripciones/updateDenegar",
    inscripciones_updateCambiarFecha:"oficio/inscripciones/updateCambiarFecha",
    inscripciones_TarjetaColaOficio:"oficio/inscripciones/TarjetaColaOficio",
    inscripciones_busquedaTarjeta:"oficio/inscripciones/busquedaTarjeta",
    //FIN DE INSCRIPCIONES

    bajasTemporales_comboEstado:"oficio/bajasTemporales/comboEstado",
    bajasTemporales_busquedaBajasTemporales:"oficio/bajasTemporales/busquedaBajasTemporales",
    bajasTemporales_updateBajaTemporal:"oficio/bajasTemporales/updateBaja",
    bajasTemporales_saveBajaTemporal:"oficio/bajasTemporales/saveBajaTemporal",
    bajasTemporales_nuevaBajaTemporal:"oficio/bajasTemporales/nuevaBajaTemporal",
    bajasTemporales_deleteBajaTemporal:"oficio/bajasTemporales/deleteBajaTemporal",
    //FIN DE BAJAS TEMPORALES

    //justificacion express
    justificacionExpres_busqueda: "oficio/busquedaJustificacionExpres",

    //CARGAS MASIVAS OFICIO
    busquedaGuardia_guardia: "combo/guardias",
    cargasMasivasOficio_decargarModelo: "oficio/cargasMasivasOficio/descargarModelo",
    cargasMasivasOficio_uploadFileIT: "oficio/cargasMasivasOficio/uploadFileIT",
    cargasMasivasOficio_uploadFileBT: "oficio/cargasMasivasOficio/uploadFileBT",

    //DESIGNAS
    designas_tipoDesignas:"oficio/designas/comboTipoDesigna",
    combo_comboJuzgadoDesignaciones: "combo/comboJuzgadoDesignaciones",
    combo_comboModulosDesignaciones: "oficio/comboModulo",
    combo_comboProcedimientosDesignaciones: "oficio/comboProcedimientos",
    designaciones_busqueda: "oficio/busquedaDesignaciones",
    parametros_search: "parametros/search",
    designaciones_listaContrarios: "oficio/designas/busquedaListaContrarios",
    designaciones_listaInteresados: "oficio/designas/busquedaListaInteresados",
    designaciones_deleteContrario:"oficio/designas/deleteContrario",
    designaciones_deleteInteresado:"oficio/designas/deleteInteresado",
    designaciones_insertInteresado:"oficio/designas/insertInteresado",
    designaciones_insertContrario:"oficio/designas/insertContrario",
    create_NewDesigna: "oficio/designas/createnewDesigna",
    actuaciones_designacion: "oficio/designas/busquedaActDesigna",
    actuaciones_designacion_anular: "oficio/designas/anularActDesigna",
    actuaciones_designacion_reactivar: "oficio/designas/reactivarActDesigna",

    //SALTOS Y COMPENSACIONES
    saltosCompensacionesOficio_buscar: "oficio/saltosCompensaciones/buscarSaltosOCompensaciones",
    saltosCompensacionesOficio_guardar: "oficio/saltosCompensaciones/guardarSaltosCompensaciones",
    saltosCompensacionesOficio_anular: "oficio/saltosCompensaciones/anularSaltosCompensaciones",
    saltosCompensacionesOficio_borrar: "oficio/saltosCompensaciones/borrarSaltosCompensaciones",
    saltosCompensacionesOficio_comboColegiados: "oficio/saltosCompensaciones/searchLetradosTurno",
}