export let endpoints_EJG_Comision: any = {
    busquedaCol_colegioComision: "ejgComision/filtros-ejg/colegioComision",
    filtrosejg_comboTipoEJGColegioComision: "ejgComision/filtros-ejg/comboTipoEJGColegioComision",
    combo_guardiaPorTurnoComision:"ejgComision/filtros-ejg/guardias/",
    busquedaFundamentosCalificacion_comboDictamenComision:"ejgComision/filtros-ejg/comboDictamenComision",
    filtrosejg_comboEJGColegioComision: "ejgComision/filtros-ejg/comboEJGColegioComision",
    filtrosejg_comboEstadoEJGComision: "ejgComision/filtros-ejg/comboEstadoEJGComision",
    filtrosejg_comboAnioActaComision: "ejgComision/filtros-ejg/comboAnioActaComision",
    filtrosejg_comboResolucionComision: "ejgComision/filtros-ejg/comboResolucionComision",
    filtrosejg_comboFundamentoJuridComision: "ejgComision/filtros-ejg/comboFundamentoJuridComision",
    filtrosejg_busquedaEJGComision: "ejgComision/filtros-ejg/busquedaEJGComision",
    filtrosejg_comboJuzgadosComision: "ejgComision/filtros-ejg/comboJuzgadosComision",
    filtrosejg_comboPonenteComision: "ejgComision/filtros-ejg/comboPonenteComision",
    filtrosejg_comboTurnoComision: "ejgComision/filtros-ejg/comboTurnosTipoComision",
    postDatosActualizarComision: "ejgComision/filtros-ejg/datosActualizar",
    obligatoriedadResolucion:"ejgComision/filtros-ejg/obligatoriedadResolucion",
    filtrosejg_comboPresidente: "ejgComision/filtros-ejg/comboPresidente",
    filtrosejg_comboSecretario: "ejgComision/filtros-ejg/comboSecretario",
    filtrosejg_busquedaActas: "acta/filtros-acta/busquedaActas",
    filtrosejg_editarResolucionFundamento: "ejgComision/filtros-ejg/editarResolucionFundamento",
    filtrosejg_borrarResolucionFundamento: "ejgComision/filtros-ejg/borrarResolucionFundamento",
    filtrosejg_editarPonente: "ejgComision/filtros-ejg/editarPonente",
    filtrosejg_borrarPonente: "ejgComision/filtros-ejg/borrarPonente",
    filtrosejg_editarActaAnio: "ejgComision/filtros-ejg/editarActaAnio",
    filtrosejg_borrarActaAnio: "ejgComision/filtros-ejg/borrarActaAnio",
    filtrosejg_comboSufijo: "acta/filtros-acta/comboSufijoActa",
    filtrosejg_anadirEJGPendientesCAJG:"acta/filtros-acta/anadirEJGPendientesCAJG",
    filtrosejg_guardarActa:"acta/filtros-acta/guardarActa",
    filtrosejg_getActa: "acta/filtros-acta/getActa",
    filtrosejg_borrar: "acta/filtros-acta/borrarActas",
    filtrosejg_abrirActa: "acta/filtros-acta/abrirActa",
    filtrosejg_cerrarActa: "acta/filtros-acta/cerrarActa"



}
