export let endpoints_facturacionPyS: any = {
    facturacionPyS_getCuentasBancarias:  "facturacionPyS/getCuentasBancarias",
    facturacionPyS_borrarCuentasBancarias:  "facturacionPyS/borrarCuentasBancarias",
    facturacionPyS_getSeriesFacturacion:  "facturacionPyS/getSeriesFacturacion",
    facturacionPyS_comboCuentaBancaria: "facturacionPyS/comboCuentasBancarias",
    facturacionPyS_comboSufijo: "facturacionPyS/comboSufijos",
    facturacionPyS_comboEtiquetas: "facturacionPyS/comboEtiquetas",
    facturacionPyS_comboDestinatarios: "facturacionPyS/comboDestinatarios",
    facturacionPyS_comboContadores: "facturacionPyS/comboContadores",
    facturacionPyS_comboContadoresRectificativas: "facturacionPyS/comboContadoresRectificativas",
    facturacionPyS_eliminaSerieFacturacion:  "facturacionPyS/eliminaSerieFacturacion",
    facturacionPyS_reactivarSerieFacturacion:  "facturacionPyS/reactivarSerieFacturacion",
    facturacionPyS_comboPlanificacion: "facturacionPyS/comboPlanificacion",
    facturacionPyS_guardarSerieFacturacion: "facturacionPyS/guardarSerieFacturacion",
    facturacionPyS_getEtiquetasSerie: "facturacionPyS/getEtiquetasSerie",
    facturacionPyS_getDestinatariosSeries: "facturacionPyS/getDestinatariosSeries",
    facturacionPyS_comboPlantillasEnvio: "facturacionPyS/comboPlantillasEnvio",
    facturacionPyS_getFormasPagosDisponiblesSeries: "facturacionPyS/getFormasPagosDisponiblesSeries",
    facturacionPyS_getFormasPagosSerie: "facturacionPyS/getFormasPagosSerie",
    facturacionPyS_comboModelosComunicacion: "facturacionPyS/comboModelosComunicacion",
    facturacionPyS_getContadoresSerie: "facturacionPyS/getContadoresSerie",
    facturacionPyS_getContadoresRectificativasSerie: "facturacionPyS/getContadoresRectificativasSerie",
    facturacionPyS_guardarEtiquetasSerieFacturacion: "facturacionPyS/guardarEtiquetasSerieFacturacion",
    facturacionPyS_guardarFormasPagosSerie: "facturacionPyS/guardarFormasPagosSerie",
}