export let endpoints_remesa: any = {
    filtrosremesas_comboEstadoRemesa: "remesasEnvio/comboEstadoRemesa",
    filtrosremesas_buscarRemesa: "remesasEnvio/buscarRemesas",
    listadoremesas_borrarRemesa: "remesasEnvio/borrarRemesas",
    ficharemesas_listadoEstadosRemesa: "remesasEnvio/listadoEstadosRemesa",
    ficharemesas_getUltimoRegistroRemesa: "remesasEnvio/getUltimoRegitroRemesa",
    ficharemesas_guardarRemesa: "remesasEnvio/guardarRemesa",
    ficharemesas_getEJGRemesa: "remesasEnvio/getEJGRemesa",
    ficharemesas_borrarExpedientesRemesa: "remesasEnvio/borrarExpedientesRemesa",
    ficharemesas_getAcciones: "remesasEnvio/getAcciones",
    ficharemesa_ejecutaOperacionRemesa: "remesasEnvio/ejecutaOperacionRemesa",
    ficharemesa_descargarLogErrores: "remesasEnvio/descargarLogErrores",
    ficharemesa_descargar: "remesasEnvio/descargar",
    remesasResultados_buscarRemesasResultados: "remesasResultado/buscarRemesasResultado",
    remesasResultados_descargarFicheros: "remesasResultado/descargarFicheros",
    remesasResultados_recuperarDatosContador: "remesasResultado/recuperarDatosContador",
    remesasResultados_guardarRemesaResultado: "remesasResultado/guardarRemesaResultado",
    remesasResolucion_buscarRemesasResolucion: "remesasResoluciones/buscarRemesasResoluciones",
    remesasResoluciones_obtenerOperacionTipoAccion: "remesasResoluciones/obtenerOperacionTipoAccion",
    remesasResoluciones_descargarRemesasResolucion: "remesasResoluciones/descargarRemesasResolucion",
    remesasResoluciones_obtenerResoluciones: "remesasResoluciones/obtenerResoluciones",
    remesasResoluciones_guardarRemesaResolucion: "remesasResoluciones/guardarRemesaResolucion",
    remesasResoluciones_actualizarRemesaResolucion: "remesasResoluciones/actualizarRemesaResolucion",
    remesasResoluciones_recuperarDatosContador: "remesasResoluciones/recuperarDatosContador"
}