export let endpoints_PyS: any = {
    PyS_savePagoCompraSuscripcion: "pys/savePagoCompraSuscripcion",
    PyS_getFichaCompraSuscripcion: "pys/getFichaCompraSuscripcion",
    PyS_solicitarCompra: "pys/solicitarCompra",
    PyS_aprobarCompra: "pys/aprobarCompra",
    PyS_denegarPeticion: "pys/denegarPeticion",
    PyS_comboEstadosFactura: "pys/comboEstadosFactura",
    PyS_getListaCompraProductos: "pys/getListaCompraProductos",
    PyS_denegarPeticionMultiple: "/pys/denegarPeticionMultiple",
    PyS_aprobarCompraMultiple: "/pys/aprobarCompraMultiple",
    PyS_getListaProductosCompra: "/pys/getListaProductosCompra",
    PyS_getPermisoModificarImporteProducto: "/pys/getPermisoModificarImporteProducto",
    PyS_updateProductosPeticion: "/pys/updateProductosPeticion",
    PyS_getFacturasPeticion: "/pys/getFacturasPeticion",
    PyS_getDescuentosPeticion: "/pys/getDescuentosPeticion",
    PyS_saveAnticipoPeticion: "/pys/saveAnticipoPeticion",
    PyS_anularPeticion: "/pys/anularPeticion",
    PyS_getListaSuscripciones: "/pys/getListaSuscripciones",
    PyS_getListaServiciosSuscripcion: "/pys/getListaServiciosSuscripcion",
    PyS_solicitarSuscripcion: "pys/solicitarSuscripcion",
    PyS_aprobarSuscripcion: "pys/aprobarSuscripcion",
    serviciosBusqueda_comboTiposMultiple: "pys/listadoTipoServicioByIdCategoriaMultiple",
}