export let endpoints_justiciables: any = {

    busquedaJusticiables_comboRoles: "justiciables/busquedaJusticiables/comboRoles",
    gestionJusticiables_getTelefonos: "justiciables/gestionJusticiables/getTelefonos",
    gestionJusticiables_comboMinusvalias: "justiciables/gestionJusticiables/comboMinusvalias",
    gestionJusticiables_comboProfesiones: "justiciables/gestionJusticiables/comboProfesiones",
    gestionJusticiables_searchJusticiable: "justiciables/gestionJusticiables/searchJusticiable",
    busquedaJusticiables_searchJusticiables: "justiciables/busquedaJusticiables/searchJusticiables",
    gestionJusticiables_comboPoblacion: "justiciables/gestionJusticiables/comboPoblacion",
    gestionJusticiables_comboTipoVias: "justiciables/gestionJusticiables/comboTipoVias",
    gestionJusticiables_comboTipoVias2: "justiciables/gestionJusticiables/comboTipoVias2",
    gestionJusticiables_createJusticiable: "justiciables/gestionJusticiables/createJusticiable",
    gestionJusticiables_updateJusticiable: "justiciables/gestionJusticiables/updateJusticiable",
    gestionJusticiables_updateDatosSolicitudJusticiable: "justiciables/gestionJusticiables/updateDatosSolicitudJusticiable",
    gestionJusticiables_createDatosSolicitudJusticiable: "justiciables/gestionJusticiables/createDatosSolicitudJusticiable",
    gestionJusticiables_searchAsuntosJusticiable: "justiciables/gestionJusticiables/searchAsuntosJusticiable",
    gestionJusticiables_getJusticiableByNif: "justiciables/gestionJusticiables/getJusticiableByNif",
    gestionJusticiables_getJusticiableByIdPersona: "justiciables/gestionJusticiables/getJusticiableByIdPersona",
    gestionJusticiables_associateRepresentante: "justiciables/gestionJusticiables/associateRepresentante",
    gestionJusticiables_disassociateRepresentante: "justiciables/gestionJusticiables/disassociateRepresentante",
    gestionJusticiables_comboGruposLaborales: "justiciables/gestionJusticiables/comboGruposLaborales",
    gestionJusticiables_comboParentesco: "justiciables/gestionJusticiables/comboParentesco",
    gestionJusticiables_comboTiposIngresos: "justiciables/gestionJusticiables/comboTiposIngresos",
    gestionJusticiables_updateUnidadFamiliar: "justiciables/gestionJusticiables/updateUnidadFamiliar",
    gestionJusticiables_getSolicitante: "justiciables/gestionJusticiables/getSolicitante",
    gestionJusticiables_asociarJusticiableDesgina: "justiciables/gestionJusticiableService/asociarDesignacion",
    gestionJusticiables_asociarJusticiableEjg: "justiciables/gestionJusticiableService/asociarEJG",
    gestionJusticiables_asociarJusticiableAsistencia:"justiciables/gestionJusticiableService/asociarAsistencia",
    gestionJusticiables_asociarJusticiableSOJ:"justiciables/gestionJusticiableService/asociarSOJ" 

}
