export let endpoints_maestros: any = {
    fichaZonas_getPartidosJudiciales: "maestros/fichaZonas/partidosJudiciales",
    gestionZonas_searchZones: "maestros/gestionZonas/searchZones",
    fichaZonas_createZones: "maestros/fichaZonas/createZones",
    fichaZonas_searchSubzones: "maestros/fichaZonas/searchSubzones",
    fichaZonas_searchGroupZone: "maestros/fichaZonas/searchGroupZone",
    fichaZonas_updateGroupZone: "maestros/fichaZonas/updateGroupZone",
    fichaZonas_createGroupZone: "maestros/fichaZonas/createGroupZone",
    fichaZonas_updateZones: "maestros/fichaZonas/updateZones",
    fichaZonas_createZone: "maestros/fichaZonas/createZone",
    fichaZonas_deleteZones: "maestros/fichaZonas/deleteZones",
    fichaZonas_deleteGroupZones: "maestros/fichaZonas/deleteGroupZones",
    fichaZonas_activateGroupZones: "maestros/fichaZonas/activateGroupZones",

    fichaAreas_getJurisdicciones: "maestros/areasMaterias/jurisdicciones",
    fichaAreas_searchAreas: "maestros/areasMaterias/searchAreas",
    fichaAreas_deleteAreas: "maestros/areasMaterias/deleteAreas",
    fichaAreas_updateAreas: "maestros/areasMaterias/updateAreas",
    fichaAreas_createAreas: "maestros/areasMaterias/createAreas",
    fichaAreas_searchMaterias: "maestros/areasMaterias/searchMaterias",
    fichaAreas_updateMaterias: "maestros/areasMaterias/updateMaterias",
    fichaAreas_createMaterias: "maestros/areasMaterias/createMaterias",
    fichaAreas_deleteMaterias: "maestros/areasMaterias/deleteMaterias",

    busquedaJuzgados_searchCourt: "maestros/busquedaJuzgados/searchCourt",
    busquedaJuzgados_provinces: "maestros/busquedaJuzgados/provinces",
    busquedaJuzgados_population: "maestros/busquedaJuzgados/population",
    busquedaJuzgados_deleteCourt: "maestros/busquedaJuzgados/deleteCourt",
    busquedaJuzgados_activateCourt: "maestros/busquedaJuzgados/activateCourt",
    gestionJuzgados_searchProcess: "maestros/gestionJuzgados/searchProcess",
    gestionJuzgados_searchProcCourt: "maestros/gestionJuzgados/searchProcCourt",
    gestionJuzgados_createCourt: "maestros/gestionJuzgados/createCourt",
    gestionJuzgados_updateCourt: "maestros/gestionJuzgados/updateCourt",
    gestionJuzgados_associateProcess: "maestros/gestionJuzgados/associateProcess",

    gestionCostesFijos_getCosteFijos: "maestros/gestionCostesFijos/comboCosteFijos",
    gestionCostesFijos_getComboAsistencia: "maestros/gestionCostesFijos/comboAsistencia",
    gestionCostesFijos_getComboActuacion: "maestros/gestionCostesFijos/comboActuacion",
    gestionCostesFijos_searchCosteFijos: "maestros/gestionCostesFijos/searchCostesFijos",
    gestionCostesFijos_createCosteFijo: "maestros/gestionCostesFijos/createCosteFijo",
    gestionCostesFijos_deleteCostesFijos: "maestros/gestionCostesFijos/deleteCostesFijos",
    gestionCostesFijos_activateCostesFijos: "maestros/gestionCostesFijos/activateCostesFijos",
    gestionCostesFijos_updateCostesFijos: "maestros/gestionCostesFijos/updateCostesFijos",

    gestionFundamentosResolucion_searchFundamentosResolucion: "maestros/gestionFundamentosResolucion/searchFundamentosResolucion",
    gestionFundamentosResolucion_deleteFundamentosResolucion: "maestros/gestionFundamentosResolucion/deleteFundamentosResolucion",
    gestionFundamentosResolucion_activateFundamentosResolucion: "maestros/gestionFundamentosResolucion/activateFundamentosResolucion",
    gestionFundamentosResolucion_getResoluciones: "maestros/gestionFundamentosResolucion/getResoluciones",
    gestionFundamentosResolucion_createFundamentoResolucion: "maestros/gestionFundamentosResolucion/createFundamentoResolucion",
    gestionFundamentosResolucion_updateFundamentoResolucion: "maestros/gestionFundamentosResolucion/updateFundamentoResolucion",

    modulosYBasesDeCompensacion_searchModulos: "maestros/modulosybasesdecompensacion/searchModulos",
    modulosybasesdecompensacion_deleteModulos: "maestros/modulosybasesdecompensacion/deleteModulos",

    gestionPartidasPres_searchPartidasPres: "maestros/gestionPartidasPres/searchPartidasPres",
    gestionPartidasPres_eliminatePartidasPres: "maestros/gestionPartidasPres/eliminatePartidasPres",
    gestionPartidasPres_updatePartidasPres: "maestros/gestionPartidasPres/updatePartidasPres",
    gestionPartidasPres_createPartidasPres: "maestros/gestionPartidasPres/createPartidasPres",

    busquedaPrisiones_searchPrisiones: "maestros/busquedaPrisiones/searchPrisiones",
    busquedaPrisiones_provinces: "maestros/busquedaPrisiones/provinces",
    busquedaPrisiones_population: "maestros/busquedaPrisiones/population",
    busquedaPrisiones_deletePrisiones: "maestros/busquedaPrisiones/deletePrisiones",
    busquedaPrisiones_activatePrisiones: "maestros/busquedaPrisiones/activatePrisiones",
    gestionPrisiones_createPrision: "maestros/gestionPrisiones/createPrision",
    gestionPrisiones_updatePrision: "maestros/gestionPrisiones/updatePrision",
}