export let endpoints_facturacionsjcs: any = {
    combo_comboFactEstados: "combo/comboFactEstados",
    combo_partidasPresupuestarias: "combo/partidasPresupuestarias",
    combo_grupoFacturacion: "combo/grupoFacturacion",
    combo_comboFactConceptos: "combo/comboFactConceptos",
    combo_comboFactColegio: "combo/comboFactColegio",
    combo_comboPagosColegio: "combo/comboPagosColegio",
    combo_comboEstadosAbono: "combo/estadoAbonos",
    combo_comboGrupoFacturacion: "combo/grupoFacturacion",
    facturacionsjcs_buscarfacturaciones: "facturacionsjcs/buscarfacturaciones",
    facturacionsjcs_eliminarFacturacion: "facturacionsjcs/eliminarFacturacion",
    facturacionsjcs_datosfacturacion: "facturacionsjcs/datosfacturacion",
    facturacionsjcs_historicofacturacion: "facturacionsjcs/historicofacturacion",
    facturacionsjcs_saveFacturacion: "facturacionsjcs/saveFacturacion",
    facturacionsjcs_updateFacturacion: "facturacionsjcs/updateFacturacion",
    facturacionsjcs_ejecutarfacturacion: "facturacionsjcs/ejecutarfacturacion",
    facturacionsjcs_buscarCartasfacturacion: "facturacionsjcs/buscarCartasfacturacion",
    facturacionsjcs_buscarCartaspago: "facturacionsjcs/buscarCartaspago",
    facturacionsjcs_reabrirfacturacion: "facturacionsjcs/reabrirfacturacion",
    facturacionsjcs_simularfacturacion: "facturacionsjcs/simularfacturacion",
    facturacionsjcs_tarjetaConceptosfac: "facturacionsjcs/tarjetaConceptosfac",
    facturacionsjcs_saveConceptosFac: "facturacionsjcs/saveConceptosFac",
    facturacionsjcs_updateConceptosFac: "facturacionsjcs/updateConceptosFac",
    facturacionsjcs_deleteConceptosFac: "facturacionsjcs/deleteConceptosFac",
    facturacionsjcs_datospagos: "facturacionsjcs/datospagos",
    facturacionsjcs_numApuntes: "facturacionsjcs/numApuntes",
    factuarcionsjscs_buscarAbonos : "facturacionsjcs/buscarAbonosSJCS",

}
