export let SigaConstants: any = {
    SCS_JUSTICIABLE: "0",
    SCS_SOLICITANTE_EJG: "1",
    SCS_UNIDAD_FAMILIAR_EJG: "2",
    SCS_CONTRARIO_EJG: "3",
    SCS_DESIGNACION: "4",
    SCS_CONTRARIO_ASISTENCIA: "5",
    SCS_SOLICITANTE_DESIGNACION: "6",
    SCS_SOLICITANTE_ASISTENCIA: "7",

    EDAD_ADULTA: 18
}